// InExplorer_Settings.h

#pragma once

#define NM_EX_INEXPLORER	_T("InExplorer")

#define MD_EX_MAIN			_T("InExplorer.exe")
#define MD_EX_MAINLX		_T("InExplorerLX.dll")
#define MD_EX_MAINLXP		_T("InExplorerLX.lxp")
#define MD_EX_SHORTCUT		_T("InExplorer.lnk")
#define MD_EX_TRIAL			_T("TIEX0660.drv")

#define RK_EX_ROOT			_T("Software\\InSuite\\InExplorer")
#define RK_EX_GENERAL		_T("Software\\InSuite\\InExplorer\\General")
#define RK_EX_VIEW			_T("Software\\InSuite\\InExplorer\\View")
#define RK_EX_BROWSER		_T("Software\\InSuite\\InExplorer\\Browser")
#define RK_EX_FIND			_T("Software\\InSuite\\InExplorer\\Find")
#define RK_EX_ZIP			_T("Software\\InSuite\\InExplorer\\ZIP")

#define RV_EX_STARTUP		_T("Startup Folder")
#define RV_EX_OPENFOLDER	_T("Open Folder")
#define RV_EX_LASTOPENED	_T("Last Opened")
#define RV_EX_MODE			_T("Mode")
#define RV_EX_LAYOUT		_T("Layout")
#define RV_EX_FOLDERBAR		_T("Folder Bar")
#define RV_EX_STATUSBAR		_T("Status Bar")
#define RV_EX_VIEWSTYLE		_T("View Style")
#define RV_EX_FULLROWSELECT	_T("Full Row Select")
#define RV_EX_AUTOWIDTH		_T("Auto Column Width")
#define RV_EX_MAXAUTOWIDTH	_T("Max Auto Column Width")
#define RV_EX_NAMEEDITOR	_T("Use Name Editor")
#define RV_EX_DOUBLETAP		_T("Double Tap Activation")
#define RV_EX_MULTISELECT	_T("Multi Select")
#define RV_EX_DATEFORMAT	_T("Date Format")
#define RV_EX_SIZEFORMAT	_T("Size Format")
#define RV_EX_SHOWEXT		_T("Show Extension")
#define RV_EX_SHOWROM		_T("Show ROM")
#define RV_EX_SHOWSYSTEM	_T("Show System")
#define RV_EX_SHOWHIDDEN	_T("Show Hidden")
#define RV_EX_FILTER		_T("Filter")
#define RV_EX_FROM			_T("From")
#define RV_EX_COMPRESSLEVEL	_T("Compress Level")
#define RV_EX_CODEPAGESET	_T("Code Page Set")
#define RV_EX_CODEPAGE		_T("Code Page")
