// InternetX.h

#pragma once

#include "InAPI.h"
#include "wininet.h"

#ifndef INLIB_INET_SERVICE_FTP
#define INLIB_INET_SERVICE_FTP		INTERNET_SERVICE_FTP
#define INLIB_INET_SERVICE_HTTP		INTERNET_SERVICE_HTTP
#define INLIB_INET_SERVICE_GOPHER	INTERNET_SERVICE_GOPHER
#endif

#ifndef INLIB_INET_SERVICE_UNK
#define INLIB_INET_SERVICE_UNK		0x1000
#define INLIB_INET_SERVICE_FILE		(INLIB_INET_SERVICE_UNK +  1)
#define INLIB_INET_SERVICE_MAILTO	(INLIB_INET_SERVICE_UNK +  2)
#define INLIB_INET_SERVICE_MID		(INLIB_INET_SERVICE_UNK +  3)
#define INLIB_INET_SERVICE_CID		(INLIB_INET_SERVICE_UNK +  4)
#define INLIB_INET_SERVICE_NEWS		(INLIB_INET_SERVICE_UNK +  5)
#define INLIB_INET_SERVICE_NNTP		(INLIB_INET_SERVICE_UNK +  6)
#define INLIB_INET_SERVICE_PROSPERO	(INLIB_INET_SERVICE_UNK +  7)
#define INLIB_INET_SERVICE_TELNET	(INLIB_INET_SERVICE_UNK +  8)
#define INLIB_INET_SERVICE_WAIS		(INLIB_INET_SERVICE_UNK +  9)
#define INLIB_INET_SERVICE_AFS		(INLIB_INET_SERVICE_UNK + 10)
#define INLIB_INET_SERVICE_HTTPS	(INLIB_INET_SERVICE_UNK + 11)
#endif

// The length of szServer and szObject must be larger than INTERNET_MAX_URL_LENGTH + 1.
BOOL	INAPI_API	ParseURLX(LPCTSTR lpszURL, DWORD& dwServiceType, LPTSTR szServer, LPTSTR szObject, INTERNET_PORT& nPort);
int		INAPI_API	HTTPQueryX(LPTSTR szAddress, LPTSTR szResponse, LPDWORD lpdwResponseLength);
