//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by InXDCppc.rc
//
#define IDD_PROPERTIES_DIALOG           7000
#define IDD_PROPTIME_DIALOG             7001
#define IDD_PROPATTRIBUTES_DIALOG       7002
#define IDD_FONT_PAGE                   7003
#define IDD_FONT_DIALOG                 7004
#define IDD_CONFIRM_DIALOG              7005
#define IDD_EXIST_DIALOG                7006
#define IDD_PROCESS_SINGLE_DIALOG       7007
#define IDD_PROCESS_DOUBLE_DIALOG       7008
#define IDD_TREE_DIALOG                 7009
#define IDD_SAVE_DIALOG                 7010
#define IDD_IMAGE_DIALOG                7011
#define IDD_REGISTER_DIALOG             7012
#define IDC_PROP_NAME_EDIT              7050
#define IDC_PROP_NAME                   7051
#define IDC_PROP_TYPE_H                 7052
#define IDC_PROP_TYPE                   7053
#define IDC_PROP_LOCATION_H             7054
#define IDC_PROP_LOCATION               7055
#define IDC_PROP_SIZE_H                 7056
#define IDC_PROP_SIZE                   7057
#define IDC_PROP_CONTAINS_H             7058
#define IDC_PROP_CONTAINS               7059
#define IDC_PROP_CAPACITY_H             7060
#define IDC_PROP_CAPACITY               7061
#define IDC_PROP_TIME                   7062
#define IDC_PROP_ATTRIBUTES             7063
#define IDC_PROP_CREATED_H              7064
#define IDC_PROP_CREATED                7065
#define IDC_PROP_MODIFIED_H             7066
#define IDC_PROP_MODIFIED               7067
#define IDC_PROP_ACCESSED_H             7068
#define IDC_PROP_ACCESSED               7069
#define IDC_PROP_READONLY               7070
#define IDC_PROP_HIDDEN                 7071
#define IDC_PROP_ARCHIVE                7072
#define IDC_PROP_SYSTEM                 7073
#define IDC_PROP_ROM                    7074
#define IDC_FNTP_FONT_H                 7075
#define IDC_FNTP_FONT                   7076
#define IDC_FNTP_DEFAULT                7077
#define IDC_FNTP_SIZE_H                 7078
#define IDC_FNTP_SIZE                   7079
#define IDC_FNTP_COLOR_H                7080
#define IDC_FNTP_COLOR                  7081
#define IDC_FNTP_STYLE_H                7082
#define IDC_FNTP_BOLD                   7083
#define IDC_FNTP_ITALIC                 7084
#define IDC_FNTP_UNDERLINE              7085
#define IDC_FNTP_CLEARTYPE              7086
#define IDC_FNTP_PREVIEW_H              7087
#define IDC_FNTP_PREVIEW                7088
#define IDC_FNTD_FONT_H                 7089
#define IDC_FNTD_FONT                   7090
#define IDC_FNTD_DEFAULT                7091
#define IDC_FNTD_SIZE_H                 7092
#define IDC_FNTD_SIZE                   7093
#define IDC_FNTD_COLOR_H                7094
#define IDC_FNTD_COLOR                  7095
#define IDC_FNTD_STYLE_H                7096
#define IDC_FNTD_BOLD                   7097
#define IDC_FNTD_ITALIC                 7098
#define IDC_FNTD_UNDERLINE              7099
#define IDC_FNTD_CLEARTYPE              7100
#define IDC_FNTD_PREVIEW_H              7101
#define IDC_FNTD_PREVIEW                7102
#define IDC_CONF_MESSAGE                7103
#define IDC_CONF_DOALL                  7104
#define IDC_EXIS_MESSAGE                7105
#define IDC_EXIS_REPLACE                7106
#define IDC_EXIS_NOTCHANGE              7107
#define IDC_EXIS_DOCONFLICT             7108
#define IDC_PRCS_FILENAME               7109
#define IDC_PRCS_PROGRESS               7110
#define IDC_PRCS_STATUS                 7111
#define IDC_PRCD_FILENAME               7112
#define IDC_PRCD_PROGRESS               7113
#define IDC_PRCD_TOTAL                  7114
#define IDC_PRCD_STATUS                 7115
#define IDC_TREE_TREE                   7116
#define IDC_SAVE_NAME_H                 7117
#define IDC_SAVE_NAME                   7118
#define IDC_SAVE_FOLDER_H               7119
#define IDC_SAVE_FOLDER                 7120
#define IDC_SAVE_BROWSE                 7121
#define IDC_SAVE_TYPE_H                 7122
#define IDC_SAVE_TYPE                   7123
#define IDC_IMGE_TREE                   7124
#define IDC_REGI_EMAIL_H                7125
#define IDC_REGI_EMAIL                  7126
#define IDC_REGI_SERIAL_H               7127
#define IDC_REGI_SERIAL                 7128
#define IDC_REGI_PERIOD                 7129
#define IDS_MENU_OKAY                   7600
#define IDS_MENU_OPEN                   7601
#define IDS_MENU_SAVE                   7602
#define IDS_MENU_SELECT                 7603
#define IDS_MENU_CANCEL                 7604
#define IDS_MENU_EXPAND                 7605
#define IDS_MENU_COLLAPSE               7606
#define IDS_MENU_NEW_FOLDER             7607
#define IDS_MENU_RENAME                 7608
#define IDS_MENU_DELETE                 7609
#define IDS_MENU_REFRESH                7610
#define IDS_MENU_PROPERTIES             7611
#define IDS_MENU_EXECUTE                7612
#define IDS_FILE_BYTES                  7613
#define IDS_FILE_KILOBYTES              7614
#define IDS_FILE_MEGABYTES              7615
#define IDS_FILE_GIGABYTES              7616
#define IDS_FILE_TERABYTES              7617
#define IDS_FILE_NEW_FOLDER             7618
#define IDS_FONT_HEADER                 7619
#define IDS_FONT_AUTOMATIC              7620
#define IDS_FONT_CANCEL                 7621
#define IDS_FONT_PREVIEW                7622
#define IDS_DELE_HEADER                 7623
#define IDS_DELE_CONFIRM_TITLE          7624
#define IDS_DELE_CONFIRM_ONE            7625
#define IDS_DELE_CONFIRM_MULTI          7626
#define IDS_DELE_FOLDER                 7627
#define IDS_DELE_COMPLETE               7628
#define IDS_DELE_INCOMPLETE             7629
#define IDS_DELE_PREPARING              7630
#define IDS_DELE_DELETING               7631
#define IDS_DELE_CALCULATING            7632
#define IDS_DELE_REMAIN                 7633
#define IDS_DELC_READONLY               7634
#define IDS_DELC_HIDDEN                 7635
#define IDS_DELC_SYSTEM                 7636
#define IDS_FOLD_HEADER                 7637
#define IDS_FILE_TITLEERROR             7638
#define IDS_FILE_INVALIDNAME            7639
#define IDS_CPCN_MESSAGE                7640
#define IDS_COPY_HEADER                 7641
#define IDS_COPY_REPLACE                7642
#define IDS_COPY_NOTCHANGE              7643
#define IDS_COPY_COMPLETE               7644
#define IDS_COPY_INCOMPLETE             7645
#define IDS_COPY_PREPARING              7646
#define IDS_COPY_COPYING                7647
#define IDS_COPY_CALCULATING            7648
#define IDS_COPY_REMAIN                 7649
#define IDS_FILE_HEADER                 7650
#define IDS_SAVE_HEADER                 7651
#define IDS_SAVE_FOLDER_HEADER          7652
#define IDS_SAVE_TITLE                  7653
#define IDS_SAVE_OVERWRITE              7654
#define IDS_IMGE_HEADER                 7655
#define IDS_IMGE_NOIMAGE                7656
#define IDS_IMGE_WIDTH                  7657
#define IDS_IMGE_HEIGHT                 7658
#define IDS_MOVE_HEADER                 7659
#define IDS_MOVE_REPLACE                7660
#define IDS_MOVE_NOTCHANGE              7661
#define IDS_MOVE_COMPLETE               7662
#define IDS_MOVE_INCOMPLETE             7663
#define IDS_MOVE_PREPARING              7664
#define IDS_MOVE_MOVING                 7665
#define IDS_MOVE_CALCULATING            7666
#define IDS_MOVE_REMAIN                 7667
#define IDS_PROP_FILES                  7668
#define IDS_PROP_FOLDERS                7669
#define IDS_PROP_MULTIITEMS             7670
#define IDS_PROP_MULTITYPES             7671
#define IDS_PROP_CAPACITY               7672
#define IDS_PROP_TIME                   7673
#define IDS_PROP_ATTRIBUTES             7674
#define IDS_TRNF_HEADER                 7675
#define IDS_TRNF_DOWNLOADNAME           7676
#define IDS_TRNF_UPLOADNAME             7677
#define IDS_TRNF_GETTINGINFO            7678
#define IDS_TRNF_RETRIEVING             7679
#define IDS_TRNF_UPLOADING              7680
#define IDS_TRNF_RESOLVING              7681
#define IDS_TRNF_RESOLVED               7682
#define IDS_TRNF_CONNECTING             7683
#define IDS_TRNF_CONNECTED              7684
#define IDS_TRNF_REDIRECTING            7685
#define IDS_TRNF_ABORTING               7686
#define IDS_TRNF_BYTES                  7687
#define IDS_TRNF_KILOBYTES              7688
#define IDS_TRNF_MEGABYTES              7689
#define IDS_TRNF_GIGABYTES              7690
#define IDS_TRNF_TERABYTES              7691
#define IDS_TRNF_OF                     7692
#define IDS_TRNF_TIMEREMAIN             7693
#define IDS_TRNF_TIMELEFT               7694
#define IDS_TRNF_ERRASKOVERWRITE        7695
#define IDS_TRNF_ERRLOCALOPEND          7696
#define IDS_TRNF_ERRLOCALOPENU          7697
#define IDS_TRNF_ERRFILESEEK            7698
#define IDS_TRNF_ERRFTP                 7699
#define IDS_TRNF_ERRHTTP                7700
#define IDS_TRNF_ERRTHREAD              7701
#define IDS_TRNF_ERRCONNECT             7702
#define IDS_TRNF_ERROPENFILE            7703
#define IDS_TRNF_ERRDOWNLOAD            7704
#define IDS_TRNF_ERRUPLOAD              7705
#define IDS_TRNF_ERRSERVERRSP           7706
#define IDS_TRNF_ERRHTTPRSP             7707
#define IDS_REGI_REGISTER               7708
#define IDS_REGI_TRYMORE                7709
#define IDS_REGI_CLOSE                  7710
#define IDS_REGI_TITLE                  7711
#define IDS_REGI_SUCCESS                7712
#define IDS_REGI_FAILED                 7713
#define IDS_REGI_TIMELEFT               7714
#define IDS_REGI_TIMEEXPIRED            7715
#define IDS_REGI_TIMEREGISTERED         7716
#define IDS_ZIPX_HEADERZ                7717
#define IDS_ZIPX_HEADERU                7718
#define IDS_ZIPX_COMPLETE               7719
#define IDS_ZIPX_PREPARINGZ             7720
#define IDS_ZIPX_PREPARINGU             7721
#define IDS_ZIPX_COMPRESSING            7722
#define IDS_ZIPX_DECOMPRESSING          7723
#define IDS_ZIPX_CALCULATING            7724
#define IDS_ZIPX_REMAINZ                7725
#define IDS_ZIPX_REMAINU                7726
#define ID_FILE_SELECT                  41001
#define ID_FILE_EXPAND                  41002
#define ID_FILE_COLLAPSE                41003
#define ID_FILE_EXECUTE                 41004
#define ID_FILE_NEW_FOLDER              41005
#define ID_FILE_RENAME                  41006
#define ID_FILE_DELETE                  41007
#define ID_FILE_REFRESH                 41008
#define ID_FILE_PROPERTIES              41009
#define ID_FOLD_SELECT                  41010
#define ID_FOLD_EXPAND                  41011
#define ID_FOLD_COLLAPSE                41012
#define ID_FOLD_NEW_FOLDER              41013
#define ID_FOLD_RENAME                  41014
#define ID_FOLD_DELETE                  41015
#define ID_FOLD_REFRESH                 41016
#define ID_FOLD_PROPERTIES              41017
#define ID_IMGE_SELECT                  41018
#define ID_IMGE_EXPAND                  41019
#define ID_IMGE_COLLAPSE                41020
#define ID_IMGE_NEW_FOLDER              45021
#define ID_IMGE_RENAME                  45022
#define ID_IMGE_DELETE                  45023
#define ID_IMGE_REFRESH                 45024
#define ID_IMGE_PROPERTIES              45025

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        7000
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         7000
#define _APS_NEXT_SYMED_VALUE           7000
#endif
#endif
